test_that("PROactive score is correct", {
  
  # Steps score (median)
  expect_equal(compute_pro_actigraph_score(1000, "steps", fun = "median") , 0)
  expect_equal(compute_pro_actigraph_score(1001, "steps", fun = "median"), 1)
  expect_equal(compute_pro_actigraph_score(2000, "steps", fun = "median"), 1)
  expect_equal(compute_pro_actigraph_score(2001, "steps", fun = "median"), 2)
  expect_equal(compute_pro_actigraph_score(4000, "steps", fun = "median"), 2)
  expect_equal(compute_pro_actigraph_score(4001, "steps", fun = "median"), 3)
  expect_equal(compute_pro_actigraph_score(6000, "steps", fun = "median"), 3)
  expect_equal(compute_pro_actigraph_score(6001, "steps", fun = "median"), 4)
  expect_equal(compute_pro_actigraph_score(6799, "steps", fun = "median"), 4)
  
  
  # VMU score (median)
  expect_equal(compute_pro_actigraph_score(100, "vmu", fun = "median") , 0)
  expect_equal(compute_pro_actigraph_score(101, "vmu", fun = "median"), 1)
  expect_equal(compute_pro_actigraph_score(200, "vmu", fun = "median"), 1)
  expect_equal(compute_pro_actigraph_score(201, "vmu", fun = "median"), 2)
  expect_equal(compute_pro_actigraph_score(300, "vmu", fun = "median"), 2)
  expect_equal(compute_pro_actigraph_score(301, "vmu", fun = "median"), 3)
  expect_equal(compute_pro_actigraph_score(500, "vmu", fun = "median"), 3)
  expect_equal(compute_pro_actigraph_score(501, "vmu", fun = "median"), 4)
  expect_equal(compute_pro_actigraph_score(599, "vmu", fun = "median"), 4)
  
  # Steps score (mean)
  expect_equal(compute_pro_actigraph_score(1300, "steps", fun = "mean") , 0)
  expect_equal(compute_pro_actigraph_score(1301, "steps", fun = "mean"), 1)
  expect_equal(compute_pro_actigraph_score(2200, "steps", fun = "mean"), 1)
  expect_equal(compute_pro_actigraph_score(2201, "steps", fun = "mean"), 2)
  expect_equal(compute_pro_actigraph_score(4000, "steps", fun = "mean"), 2)
  expect_equal(compute_pro_actigraph_score(4001, "steps", fun = "mean"), 3)
  expect_equal(compute_pro_actigraph_score(5700, "steps", fun = "mean"), 3)
  expect_equal(compute_pro_actigraph_score(5701, "steps", fun = "mean"), 4)
  expect_equal(compute_pro_actigraph_score(5799, "steps", fun = "mean"), 4)
  
  
  # VMU score (mean)
  expect_equal(compute_pro_actigraph_score(180, "vmu", fun = "mean") , 0)
  expect_equal(compute_pro_actigraph_score(181, "vmu", fun = "mean"), 1)
  expect_equal(compute_pro_actigraph_score(260, "vmu", fun = "mean"), 1)
  expect_equal(compute_pro_actigraph_score(261, "vmu", fun = "mean"), 2)
  expect_equal(compute_pro_actigraph_score(350, "vmu", fun = "mean"), 2)
  expect_equal(compute_pro_actigraph_score(351, "vmu", fun = "mean"), 3)
  expect_equal(compute_pro_actigraph_score(490, "vmu", fun = "mean"), 3)
  expect_equal(compute_pro_actigraph_score(491, "vmu", fun = "mean"), 4)
  expect_equal(compute_pro_actigraph_score(499, "vmu", fun = "mean"), 4)
  
})
