utils::globalVariables(c(
  "equations_mets", 
  "Study",
  "sed_cutpoints",
  "mvpa_cutpoints",
  "sed_lines", 
  "ratio_lines", 
  "mvpa_lines", 
  "sed_cutpoint_chosen",
  "mpa_cutpoint_chosen",
  "vpa_cutpoint_chosen",
  "axis_sed_chosen_name", 
  "axis_mvpa_chosen_name",
  "wear_time",
  "validity",
  "total_counts_axis1",
  "total_counts_vm",
  "total_steps",
  "total_kcal_wear_time",
  "minutes_SED",
  "minutes_LPA",
  "minutes_MPA",
  "minutes_VPA",
  "minutes_MVPA",
  "percent_SED",
  "percent_LPA",
  "percent_MPA",
  "percent_VPA",
  "percent_MVPA",
  "mets_hours_mvpa",
  "ratio_mvpa_sed",
  "pal", 
  "SED",
  "LPA",
  "MPA",
  "VPA",
  "METS",
  "wearing",
  "axis1",
  "axis2",
  "axis3",
  "timestamp",
  "time",
  "inclinestanding",
  "inclinesitting",
  "inclinelying",
  "everything",
  "wearing",
  "wearing_count",
  "vm",
  "steps",
  "kcal"
  
  
  
  
  
  
  ))