# Workflow derived from https://github.com/alexquant1993/shareIBC/blob/master/.github/workflows/test-coverage.yaml
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Install Linux system dependencies
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get install -y software-properties-common
          sudo apt-get update
          sudo apt-get install -y make
          sudo apt-get install -y git
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libfribidi-dev
          sudo apt-get install -y libgit2-dev
          sudo apt-get install -y libharfbuzz-dev
          sudo apt-get install -y libicu-dev
          sudo apt-get install -y libssl-dev
          sudo apt-get install -y libxml2-dev
          sudo apt-get install -y libsodium-dev
          sudo apt-get install -y python3
          sudo apt-get install -y python3-pip
          sudo apt-get install -y python3-venv

      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
          
      - name: Install activAnalyzer
        shell: bash
        run: R CMD INSTALL --preclean .
        
      - name: Install covr
        run: renv::install("covr")
        shell: Rscript {0}
        
      - name: Install testthat
        run: renv::install("testthat")
        shell: Rscript {0}

      - name: Install shinytest2
        run: renv::install("shinytest2")
        shell: Rscript {0}
        
      - name: Test coverage
        run: covr::codecov(quiet = FALSE)
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash